#!/usr/bin/env python3
import argparse
from pathlib import Path
from socket import gethostbyname

OUT_DIR = Path("out")

parser = argparse.ArgumentParser()
parser.add_argument("whitelist_file", type=argparse.FileType("r"))
parser.add_argument("--proxy-host", default="127.0.0.1")
args = parser.parse_args()


OUT_DIR.mkdir(exist_ok=True)

hostnames = [l.strip() for l in args.whitelist_file.readlines()]

traefik_hosts = ", ".join(f"`{h}`" for h in hostnames)

template = Path("docker-compose.yml.template").read_text()
(OUT_DIR / "docker-compose.yml").write_text(template.replace("@HOSTS@", traefik_hosts))


ip_addr = gethostbyname(args.proxy_host)
with (OUT_DIR / "hosts").open("w") as f:
    for h in hostnames:
        f.write(f"{ip_addr}\t{h}\n")
